"""add tags and templates

Revision ID: 3cdb9fb62df8
Revises: d52be3ddac52
Create Date: 2023-07-24 14:40:56.163554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdb9fb62df8'
down_revision = 'd52be3ddac52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_id', table_name='tag')
    op.drop_index('ix_tag_title', table_name='tag')
    op.drop_table('tag')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_table('htmltemplate_tag')
    op.drop_index('ix_htmltemplate_id', table_name='htmltemplate')
    op.drop_index('ix_htmltemplate_title', table_name='htmltemplate')
    op.drop_table('htmltemplate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('htmltemplate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_htmltemplate_title', 'htmltemplate', ['title'], unique=False)
    op.create_index('ix_htmltemplate_id', 'htmltemplate', ['id'], unique=False)
    op.create_table('htmltemplate_tag',
    sa.Column('htmltemplate_id', sa.INTEGER(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['htmltemplate_id'], ['htmltemplate.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=320), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=22), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tag_title', 'tag', ['title'], unique=False)
    op.create_index('ix_tag_id', 'tag', ['id'], unique=False)
    # ### end Alembic commands ###
